"use client";

import { useState } from "react";

interface TaskItem {
  id: string;
  title: string;
  client: string;
  due: string;
  status: "PENDING" | "IN_PROGRESS" | "COMPLETED";
}

const INITIAL_TASKS: TaskItem[] = [
  { id: "1", title: "Follow up with Rahul Sharma regarding bulk linen price review", client: "Meridian Textiles", due: "In 2 days", status: "PENDING" },
  { id: "2", title: "Verify transaction receipt parameters for widget supply contract", client: "Gupta Tech Solutions", due: "Today", status: "IN_PROGRESS" },
  { id: "3", title: "Send custom catalog specifications to Priya Nair", client: "Coastal Crafts Pvt Ltd", due: "Yesterday", status: "COMPLETED" },
  { id: "4", title: "Resolve payment link 502 gateway support ticket with stripe desk", client: "Coastal Crafts Pvt Ltd", due: "Today, 5 PM", status: "PENDING" },
  { id: "5", title: "Draft contract proposal for Q3 renewal opportunity", client: "Patel Exports", due: "Tomorrow", status: "PENDING" },
];

export default function TasksPage() {
  const [tasks, setTasks] = useState<TaskItem[]>(INITIAL_TASKS);
  const [filter, setFilter] = useState<"ALL" | "PENDING" | "COMPLETED">("ALL");
  const [newTitle, setNewTitle] = useState("");
  const [newClient, setNewClient] = useState("");
  const [newDue, setNewDue] = useState("");

  const [feedback, setFeedback] = useState("");

  function toggleComplete(id: string) {
    setTasks(
      tasks.map((t) =>
        t.id === id
          ? { ...t, status: t.status === "COMPLETED" ? "PENDING" : ("COMPLETED" as const) }
          : t
      )
    );
  }

  function handleAddTask(e: React.FormEvent) {
    e.preventDefault();
    if (!newTitle.trim()) return;

    const newTask: TaskItem = {
      id: String(tasks.length + 1),
      title: newTitle,
      client: newClient || "General Operations",
      due: newDue || "Today",
      status: "PENDING",
    };

    setTasks([newTask, ...tasks]);
    setNewTitle("");
    setNewClient("");
    setNewDue("");
    
    setFeedback("Operations task logged successfully.");
    setTimeout(() => setFeedback(""), 2000);
  }

  const filteredTasks = tasks.filter((t) => {
    if (filter === "PENDING") return t.status === "PENDING" || t.status === "IN_PROGRESS";
    if (filter === "COMPLETED") return t.status === "COMPLETED";
    return true;
  });

  const totalCount = tasks.length;
  const completedCount = tasks.filter(t => t.status === "COMPLETED").length;
  const completionRate = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  return (
    <main className="p-8 w-full overflow-y-auto bg-transparent text-ink flex-1">
      {/* Header */}
      <div className="mb-6 flex justify-between items-end border-b border-line pb-4">
        <div>
          <h1 className="text-xl font-medium tracking-tight mb-1">Operations Tasks</h1>
          <p className="text-mute text-xs">Track follow-up actions and ticket resolutions generated by AI qualification workflows.</p>
        </div>
        <div className="flex items-center gap-3">
          {feedback && (
            <span className="text-[10px] font-mono border border-signal/20 bg-signal/5 px-3 py-1 rounded-full text-signal animate-fade-in">
              {feedback}
            </span>
          )}
          <span className="text-[10px] font-mono border border-line bg-panel px-3 py-1 rounded-full text-mute font-bold">
            PENDING TASKS: {tasks.filter((t) => t.status !== "COMPLETED").length}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-6 items-start">
        {/* Left: Task Creator Form */}
        <div className="glass-panel rounded-lg p-5">
          <h2 className="text-xs uppercase tracking-wider font-semibold mb-4 text-signal">
            Log Manual Operations Task
          </h2>
          <form onSubmit={handleAddTask} className="space-y-4 text-xs">
            <div>
              <label className="block text-mute mb-1">Task Action / Title *</label>
              <input
                required
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="e.g. Call Amit regarding fabric quote"
                className="w-full bg-canvas border border-line rounded px-3 py-2 text-xs text-ink focus:outline-none focus:border-signal placeholder-mute"
              />
            </div>
            <div>
              <label className="block text-mute mb-1">Associated B2B Client</label>
              <input
                value={newClient}
                onChange={(e) => setNewClient(e.target.value)}
                placeholder="e.g. Meridian Textiles"
                className="w-full bg-canvas border border-line rounded px-3 py-2 text-xs text-ink focus:outline-none focus:border-signal placeholder-mute"
              />
            </div>
            <div>
              <label className="block text-mute mb-1">Due Date / Interval</label>
              <input
                value={newDue}
                onChange={(e) => setNewDue(e.target.value)}
                placeholder="e.g. Today, 5 PM or In 3 days"
                className="w-full bg-canvas border border-line rounded px-3 py-2 text-xs text-ink focus:outline-none focus:border-signal placeholder-mute"
              />
            </div>
            <button className="w-full py-2 bg-signal text-canvas font-semibold rounded hover:opacity-90 transition-opacity">
              Log Operations Task
            </button>
          </form>
        </div>

        {/* Center/Right split: Tasks checklist & Stats */}
        <div className="xl:col-span-3 grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Checklist (Span 2) */}
          <div className="lg:col-span-2 space-y-4">
            {/* Filters */}
            <div className="flex gap-2 border-b border-line pb-2 text-[10px] font-mono">
              {(["ALL", "PENDING", "COMPLETED"] as const).map((f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f)}
                  className={`px-3 py-1.5 border rounded uppercase ${
                    filter === f ? "text-signal border-signal/30 bg-signal/5 font-semibold" : "text-mute border-line hover:text-ink"
                  }`}
                >
                  {f} ({
                    f === "ALL" ? tasks.length :
                    f === "PENDING" ? tasks.filter(t=>t.status !== "COMPLETED").length :
                    tasks.filter(t=>t.status === "COMPLETED").length
                  })
                </button>
              ))}
            </div>

            {/* List of Tasks */}
            <div className="space-y-3">
              {filteredTasks.length === 0 ? (
                <p className="p-8 text-center text-mute text-xs font-mono">No tasks logged in this category.</p>
              ) : (
                filteredTasks.map((task) => (
                  <div
                    key={task.id}
                    onClick={() => toggleComplete(task.id)}
                    className={`glass-panel rounded-lg p-4 flex gap-4 items-start hover:border-signal/30 transition-all cursor-pointer select-none ${
                      task.status === "COMPLETED" ? "bg-signal/[0.01] border-signal/10" : ""
                    }`}
                  >
                    {/* Custom Cyber Checkbox */}
                    <div
                      className={`w-4 h-4 rounded border flex items-center justify-center mt-0.5 shrink-0 transition-colors ${
                        task.status === "COMPLETED"
                          ? "border-signal bg-signal text-canvas"
                          : "border-line bg-canvas/30"
                      }`}
                    >
                      {task.status === "COMPLETED" && (
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="4.5" className="w-2.5 h-2.5">
                          <polyline points="20 6 9 17 4 12"/>
                        </svg>
                      )}
                    </div>

                    {/* Task details */}
                    <div className="flex-1 min-w-0 text-xs">
                      <span className={`font-medium block leading-relaxed ${
                        task.status === "COMPLETED"
                          ? "line-through text-signal/45"
                          : "text-ink"
                      }`}>
                        {task.title}
                      </span>
                      <span className="text-[10px] text-mute block mt-1.5 font-mono">
                        Client: {task.client} · Due: {task.due}
                      </span>
                    </div>

                    {/* Uniform Status Badge */}
                    <span className={`w-24 text-center py-0.5 border rounded text-[9px] font-mono shrink-0 uppercase tracking-wider ${
                      task.status === "COMPLETED" ? "text-signal/70 border-signal/15 bg-signal/[0.02]" :
                      task.status === "IN_PROGRESS" ? "text-sky-400 border-sky-950/20 bg-sky-950/5" :
                      "text-amber-400 border-amber-950/20 bg-amber-950/5"
                    }`}>
                      {task.status.replace("_", " ")}
                    </span>
                  </div>
                ))
              )}
            </div>
          </div>

          {/* Stats & AI Productivity insights (Span 1) */}
          <div className="glass-panel rounded-lg p-5 space-y-5 h-fit">
            <h2 className="text-xs uppercase tracking-wider font-semibold text-signal border-b border-line/35 pb-2">
              AI Task Analytics
            </h2>

            {/* Circular Progress rate */}
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-full border-4 border-signal/15 flex items-center justify-center relative shrink-0">
                <div
                  style={{
                    transform: `rotate(${Math.min(360, (completionRate / 100) * 360)}deg)`,
                  }}
                  className="absolute inset-0 rounded-full border-4 border-signal border-t-transparent border-r-transparent transition-transform duration-300"
                />
                <span className="text-[10px] font-mono font-bold text-signal">{completionRate}%</span>
              </div>
              <div>
                <span className="text-[10px] font-mono text-mute uppercase tracking-widest block">Completion Rate</span>
                <span className="text-xs text-ink/90 font-medium block mt-0.5">{completedCount} of {totalCount} completed</span>
              </div>
            </div>

            {/* General stats */}
            <div className="border-t border-line/40 pt-4 text-[10px] font-mono text-mute space-y-2">
              <div className="flex justify-between">
                <span>Active Backlog queue:</span>
                <span className="text-amber font-bold">{tasks.filter(t=>t.status !== "COMPLETED").length} tasks</span>
              </div>
              <div className="flex justify-between">
                <span>Avg completion speed:</span>
                <span className="text-signal">2.1 hours</span>
              </div>
              <div className="flex justify-between">
                <span>AI Auto-Resolved rate:</span>
                <span className="text-signal">65%</span>
              </div>
            </div>

            {/* AI priority tips */}
            <div className="border-t border-line/40 pt-4 text-xs space-y-2.5">
              <span className="text-[10px] font-mono text-amber block font-bold">⚡ AI Recommendations</span>
              <p className="text-[11px] text-mute leading-relaxed">
                Prioritize <strong className="text-red-400">High Priority</strong> tickets (e.g. shipping delay complaints) to improve overall client CSAT ratings.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
